#!/bin/bash

target_architecture_name=${1}
arguments=${@:2}

cross_image_lookup_result="$(docker images -q crystalcross-$target_architecture_name-env)"

if [ "$cross_image_lookup_result" = "" ]; then
    echo "No built Docker images detected, please initalize using cross-crystal"
    exit
fi

docker run -v $(pwd):/build-env -w /build-env crystalcross-$target_architecture_name-env shards $arguments 

