#!/bin/bash

arguments=${@:1}
current_directory=$(pwd)

if [ -z "$2" ]
    then
        echo "arm64-elf-crystal - ARM64 Linux Crystal Cross-Compiler Wrapper (Docker)"
        echo "NOTE: Some Options May Fail"

fi

out_target=$(docker run -w /crystal-project-env -v $current_directory:/crystal-project-env docker-arm64-crystalcross-compiler crystal build --cross-compile --target "aarch64-unknown-linux-gnu" $arguments)

echo "docker run -w /crystal-project-env -v $current_directory:/crystal-project-env docker-arm64-crystalcross-compiler crystal build --cross-compile --target "aarch64-unknown-linux-gnu" $arguments"

full_out=$"${out_target/cc/aarch64-linux-gnu-gcc}"
echo $full_out
docker run -w /crystal-project-env -v $current_directory:/crystal-project-env docker-arm64-crystalcross-linker bash -c "$full_out"