#!/bin/bash

arguments=${@:1}
current_directory=$(pwd)

script_path=$(dirname $([ -L $0 ] && realpath $0 || echo $0))
build_script_path=$script_path/build

if [ -z "$2" ]
    then
        echo "arm64-elf-crystal - ARM64 Linux Crystal Cross-Compiler Wrapper (Docker)"
        echo "NOTE: Some Options May Fail"

fi

$build_script_path -o temp_out $arguments
docker run -w /crystal-project-env -v $current_directory:/crystal-project-env docker-arm64-crystalcross-emulator bash -c "./temp_out && rm temp_out && rm temp_out.o"
