#!/bin/bash

target_architecture_name=${1}
target_name=${2}
target_build_commands=${3}

cd "${0%/*}"

docker build --build-arg target_architecture_name=$target_architecture_name --build-arg target_build_commands=$target_build_commands -f cross-env-image/Dockerfile . -t $target_name

exit "$?"